######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 9 10:52:59 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += alltest.h alltestui.h
FORMS += widget.ui
SOURCES += alltest.cpp alltestui.cpp main.cpp
